### ISSUE TITLE
Disable auto-load in AR models?

### ISSUE THREAD

**Issue by joelmoss** [kaspth/conventional_extensions#5]
Following on from #3, and now I've used this gem a little more, it has become apparent that sometimes a little more control is required as to when extensions are loaded.

For example, I may have included a module (a concern) in a model, which one of the model extensions requires. This will fail due to extensions being loaded before the inclusion of the module.

So would it be possible to disable this auto loading of extensions for a given class?

**Comment by kaspth** [comment]
The library is an optimization of the base case of adding code to a class, which is why we do it directly in the class without involving the module hierarchy.

So if you're involving the module hierarchy, then you'll have to involve modules all the way or not use an extension for that off case. So you'll need to either make the extension use a module or concern and include it (can be done in the extension), or move it out of the extensions directory. 

That's the built-in way to control the loading. I'd like to have more documentation on Ruby's module system so it's easier for people to know what's going on here.

**Comment by joeldrapper** [comment]
I think it makes sense for extensions that require a module mixin to include / extend that dependency themselves. There's no harm as far as I can tell from including the same module twice. If it's already included by the main class or another extension, it'll just be a no-op.

**Comment by joelmoss** [comment]
I think I understand you, but I am inly advocating for a way to disable `load_extensions` being called automatically in AR models, so I can then control when I load extensions. For example:

```ruby
class User < ApplicationRecord
  include SomeConcerns
end
```

In the above case I need to `load_extensions` after the inclusion of `SomeConcerns`, and with non-AR classes, I can do that ...

```ruby
class User < ApplicationRecord
  include SomeConcerns
  load_extensions
end
```

**Comment by kaspth** [comment]
Yeah, I got all that, I'm just not interested in supporting it since it muddies the conceptual model (it's also technically impossible as far as I know to retain the automatic `load_extensions` if we support this). The only thing I'd be ok with is a config flag to disable the auto load in Active Record and always have it be manual.

**Comment by kaspth** [comment]
@joeldrapper also brought up the point that you could include the module within the extension too, and then the main class `include` will be a no-op. I like that too.

**Comment by joelmoss** [comment]
I think the latter would be a great option then - disabling the auto-load completely. 👌

**Comment by kaspth** [comment]
Yeah, on second thought I'm not interested in adding that based on what I've seen here. I want it to be always on for Active Records, and if you're doing anything more advanced for those off cases, you'll have to invoke the module hierarchy too — or not use an extension in that case. Thanks for the issue.

**Comment by kaspth** [comment]
By the way, I ended up changing my mind and chopping the auto-load based on #10.
